### ISSUE TITLE
runVX - Frames options non-functional

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/MIVisionX#1157]
@paveltc passing frames count does not stream down to runs, see log below.

```
runvx -frames:100 /opt/rocm/share/mivisionx/samples/gdf/canny.gdf
runvx 1.0.0
OK: using AMD OpenVX 1.3.0
csv,HEADER ,STATUS, COUNT,cur-ms,avg-ms,min-ms,clenqueue-ms,clwait-ms,clwrite-ms,clread-ms
OK: capturing 768x512 image(s) into 480x360 RGB image buffer with resize
csv,OVERALL,  PASS,     1,      ,  2.71,  2.71,  0.00,  0.00,  0.00,  0.00 (median 2.710)
> total elapsed time:   0.07 sec
Abort: Press any key to exit...
```

**Comment by kiritigowda** [comment]
caveat  -- running node like below seems to take frame option and not running the GDF

## Node - Pass for Frames
```
./bin/runvx -frames:10 -affinity:CPU -dump-profile node org.khronos.openvx.color_convert uniform-image:1920,1080,RGBA,0xaabbccdd image:1920,1080,RGB2

runvx 1.0.0
OK: using AMD OpenVX 1.3.0
csv,HEADER ,STATUS, COUNT,cur-ms,avg-ms,min-ms,clenqueue-ms,clwait-ms,clwrite-ms,clread-ms
csv,OVERALL,  PASS,    10,      ,  1.64,  0.78,  0.00,  0.00,  0.00,  0.00 (median 1.490)
> total elapsed time:   0.02 sec
> graph profile: 
 COUNT,tmp(ms),avg(ms),min(ms),max(ms),DEV,KERNEL
    10,  0.782,  1.642,  0.782,  3.336,CPU,GRAPH
    10,  0.782,  1.641,  0.782,  3.336,CPU,com.amd.openvx.ColorConvert_RGB_RGBX
```

## GDF - fail for num frames
```
./bin/runvx -frames:10 -affinity:CPU -dump-profile ../MIVisionX/tests/vision_tests/gdfs/01_absDiff.gdf 
runvx 1.0.0
OK: using AMD OpenVX 1.3.0
csv,HEADER ,STATUS, COUNT,cur-ms,avg-ms,min-ms,clenqueue-ms,clwait-ms,clwrite-ms,clread-ms
csv,OVERALL,  PASS,     1,      ,  1.18,  1.18,  0.00,  0.00,  0.00,  0.00 (median 1.181)
> total elapsed time:   0.01 sec
> graph profile: 
 COUNT,tmp(ms),avg(ms),min(ms),max(ms),DEV,KERNEL
     1,  1.181,  1.181,  1.181,  1.181,CPU,GRAPH
     1,  0.389,  0.389,  0.389,  0.389,CPU,com.amd.openvx.ChannelCopy_U8_U8
     1,  0.390,  0.390,  0.390,  0.390,CPU,com.amd.openvx.ChannelCopy_U8_U8
     1,  0.402,  0.402,  0.402,  0.402,CPU,com.amd.openvx.AbsDiff_U8_U8U8
```

**Comment by kiritigowda** [comment]
@paveltc we need to look at this one tomorrow? might be a minor args passing issue

**Comment by paveltc** [comment]
@kiritigowda We have already discussed this issue several times and we agreed that it may not be a trivial fix and you have never set any priority on fixing it.
I have looked at it tonight and after running MIVisionX-setup.py and building MIVisionX I have tried to run the canny sample.
I get the following:
`runvx 1.0.0
OK: using AMD OpenVX 1.3.0
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/svcbuild/mivisionx-deps/opencv-4.6.0/modules/highgui/src/window_gtk.cpp:635: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

Aborted (core dumped)`

Take a look at this. I think this needs to be solved prior to us continuing any work on runvx.
This issue is over a year old and it seems that it comes up once every six months. How critical is it to get this running?
Also, it would help if you put in more concrete examples of how to reproduce the problem. Please add a GDF and a command line that this always occurs with.

**Comment by kiritigowda** [comment]
@paveltc 
* Priority - what do you think the the priority on fixing an issue in a component, which is used for all our core testing, should be?
* GTK issue -  is an ssh setup issue which is unrelated to MIVisionX. You have to set `export DISPLAY` or follow this issue - https://github.com/ROCm/MIVisionX/issues/1097. I would expect someone using MIVisionX for the first time to report this issue.
* Test cases - If you would have taken a moment to go over the issue and look at the details, you could have avoided asking for the test cases. I have provided a screenshot below to make it easier to find the test cases this time.

<img width="919" alt="Screenshot 2024-10-14 at 10 49 23 AM" src="https://github.com/user-attachments/assets/4bc7c2b9-f5c8-4db1-98c5-bd02f76257ed">

**Comment by paveltc** [comment]
@kiritigowda 
The fix is the following:
runvx -frames:100,**ignore-eof** /opt/rocm/share/mivisionx/samples/gdf/canny.gdf

**Comment by paveltc** [comment]
Fixed with PR 1438.
